### PR TITLE
Add row-height as a style attribute

### PR DESCRIPTION
**Pull request by mauromorales**

### CODE REVIEW

**Comment by thiagoarrais** [comment]
Would you mind adding a test in the spec for prefixing row-height with style namespace? I'll use this PR merge to put the boy scout rule in practice and leave the campground cleaner than I've found it.

**Comment by mauromorales** [comment]
@thiagoarrais added the test, let me know if it's missing anything else, and thanks for the support :)

**Comment by westonganger** [comment]
Can you merge this?

**Comment by thiagoarrais** [comment]
This is merged as 7ad08473. Sorry.

**Comment by thiagoarrais** [comment]
@westonganger do you need this to be pushed to rubygems (or whatever people are using nowadays)?

**Pull request closed without merging**
